Sherstyuk Task02
xthebat/iu4-2k20-npio pull request #19
Opened 2020-09-15 17:22 UTC by Temikmapper

2020-09-16 10:46 UTC, xthebat requested changes
Уберите print и замените на log

2020-09-16 10:46 UTC, xthebat commented on sherstyuk_a/task02/build.gradle
> +    compile group: 'org.jetbrains.kotlin', name: 'kotlin-stdlib', version: '1.4.0'
Версию можно не писать, может быть определена из плагина

2020-09-16 10:46 UTC, xthebat commented on sherstyuk_a/task02/src/main/kotlin/matrixFuncs.kt
> +        val mat1RowsCount = mat1.count()
Если входные аргументы не валидны, то нужно бросать исключение:
throw IllegalArgumentException, либо (что лучше) использовать функцию require.

2020-09-16 10:46 UTC, xthebat commented on sherstyuk_a/task02/src/main/kotlin/vectorFuncs.kt
> +        vecCheck(this, other)
аналогично матрицам

2020-09-16 10:46 UTC, xthebat commented on sherstyuk_a/task02/src/main/kotlin/matrixFuncs.kt
> +    infix fun Mat.crossVec(other: Vec): Mat {
Имя можно использовать также cross(other: Vec) в котлине есть перегрузка методов и функций

2020-09-16 10:46 UTC, xthebat commented on sherstyuk_a/task02/src/main/kotlin/matrixFuncs.kt
> +                print(row)
не используйте print, если есть логгер, ему можно задать различный уровень логирования в зависимости от ситуации. Наименее приоритетные это log.finest { .... }

2020-09-16 10:46 UTC, xthebat commented on sherstyuk_a/task02/src/main/kotlin/matrixFuncs.kt
> +    infix fun Mat.equals(other: Mat): Boolean {
Есть оператор equals - нужно перегрузить его

2020-09-16 16:37 UTC, Temikmapper commented on sherstyuk_a/task02/src/main/kotlin/matrixFuncs.kt
> +    infix fun Mat.equals(other: Mat): Boolean {
Я правильно понимаю, что перегрузить equals так просто не получится и это можно сделать только внутри data class?

2020-09-18 06:53 UTC, xthebat approved these changes

2020-09-18 06:53 UTC, xthebat commented on sherstyuk_a/task02/src/main/kotlin/matrixFuncs.kt
> +    @JvmName("crossVec")
Для чего эта аннотация?

2020-09-18 06:53 UTC, xthebat commented on sherstyuk_a/task02/src/main/kotlin/matrixFuncs.kt
> +    infix fun Mat.equals(other: Mat): Boolean {
Хм, не data class, а просто класса достаточно. Да, с экстеншенами я всмпонил были проблемы при перегрузке именно equals.

2020-09-18 06:53 UTC, xthebat commented on sherstyuk_a/task02/build.gradle
> +    testCompile group: 'junit', name: 'junit'
А вот тут версию не надо было удалять :) Она из плагина kotlin не определится. При такой нотации gradle будет искать последнюю версию

2020-09-18 06:53 UTC, merged

2020-09-18 15:50 UTC, Temikmapper commented on sherstyuk_a/task02/src/main/kotlin/matrixFuncs.kt
> +    @JvmName("crossVec")
Аннотация даёт новою подпись для JVM, чтобы на Kotlin можно было вызывать эту функцию с одним именем, но содержащим разные типы.