Sherstyuk Task 03
xthebat/iu4-2k20-npio pull request #24
Opened 2020-09-23 20:00 UTC by Temikmapper

2020-09-24 06:55 UTC, xthebat requested changes

2020-09-24 06:55 UTC, xthebat commented on sherstyuk_a/task03/src/main/kotlin/ru/bmstu/iu4/task03/jsonParser.kt
> +    data class PersonImport(
- Классы нужно выносить в отдельные файлы
- Зачем в названии "Import"?

2020-09-24 06:55 UTC, xthebat commented on sherstyuk_a/task03/src/main/kotlin/ru/bmstu/iu4/task03/jsonParser.kt
> +    fun createRow(person: PersonImport, row: BufferedWriter) {
Логично сделать методы записи строки и таблицы в writer его extension и вынести их в отдельный файл
то есть `writer.writerTable(...), writer.writerRow(....)`

Создание writer вынести выше

2020-09-24 06:55 UTC, xthebat commented on sherstyuk_a/task03/src/main/kotlin/ru/bmstu/iu4/task03/jsonParser.kt
> +    fun printIndent(length: Int, row: BufferedWriter) {
аналогично в экстенш

2020-09-24 06:55 UTC, xthebat commented on sherstyuk_a/task03/src/main/kotlin/ru/bmstu/iu4/task03/jsonParser.kt
> +        for (i in 0 until indent - length) {
есть функция repeat(count) {  ... }

2020-09-24 06:55 UTC, xthebat commented on sherstyuk_a/task03/src/main/kotlin/ru/bmstu/iu4/task03/jsonParser.kt
> +        data.filter{ it.age in 20..30 }.forEach() {
- у forEach не нужны ()
- используйте ctrl+alt+L
- здесь лучше использовать sumByDouble

2020-09-24 06:55 UTC, xthebat commented on sherstyuk_a/task03/src/main/kotlin/ru/bmstu/iu4/task03/jsonParser.kt
> +    fun calculator(data: List<PersonImport>): Float {
название функции нужно уточнить: например calcBalanceForAge, можно сделать экстеншеном от List<PersonImport>, а age передать через параметры со значением по умолчанию

2020-09-24 20:32 UTC, Temikmapper commented on sherstyuk_a/task03/src/main/kotlin/ru/bmstu/iu4/task03/jsonParser.kt
> +    data class PersonImport(
> Зачем в названии "Import"?

Изначально я планировал, что будет два класса. Первый, то есть этот, просто распарсенный JSON с некорректными типами, например, strings вместо float в балансе. А второй содержал бы в себе как раз нормальные типы данных. Но особой необходимости я не увидел и оставил так :)

2020-09-25 09:29 UTC, xthebat commented on sherstyuk_a/task03/src/main/kotlin/ru/bmstu/iu4/task03/jsonParser.kt
> +    data class PersonImport(
Тогда лучше сразу рефакторить и писать правильные имена. Да, такая проблема встречается ее правильно решать через кастомный десериализатор, но это у нас пока за кадром, либо же делать как Вы сказали промежуточный класс.

2020-09-25 09:32 UTC, xthebat reviewed
В целом хорошо, но нужно исправить закрытие writer

2020-09-25 09:32 UTC, xthebat commented on sherstyuk_a/task03/src/main/kotlin/ru/bmstu/iu4/task03/jsonParser.kt
> +        this.close()
Вот это не правильно, а что если нужно вывести в файл или райтер еще таблицу. Правильно должно быть такое: "не вы создавали ресурс не вам его убивать".

2020-09-25 09:32 UTC, xthebat commented on sherstyuk_a/task03/src/main/kotlin/ru/bmstu/iu4/task03/jsonParser.kt
> +        this.write(person.name)
не надо писать this

2020-09-25 09:32 UTC, xthebat commented on sherstyuk_a/task03/src/main/kotlin/ru/bmstu/iu4/task03/jsonParser.kt
> +        repeat(indent - length) {
можно в одну строку

2020-09-25 15:23 UTC, xthebat approved these changes

2020-09-25 15:23 UTC, xthebat commented
Approve 3/3 + 1

2020-09-25 15:23 UTC, merged